version: "3.8"
services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    command: ["/mediamtx", "/mediamtx.yml"]

  ptz-proxy:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm ci && node server.js"
    environment:
      ROBOT_CAM_IP: ${ROBOT_CAM_IP}
      TABLE_CAM_IP: ${TABLE_CAM_IP}
      CAM_USER: ${CAM_USER}
      CAM_PASS: ${CAM_PASS}
    ports:
      - "3000:3000"
    volumes:
      - ./ptz-proxy:/app
    restart: unless-stopped

  coturn:
    image: instrumentisto/coturn
    restart: unless-stopped
    network_mode: host
    environment:
      REALM: ${TURN_REALM}
      USERNAME: ${TURN_USER}
      PASSWORD: ${TURN_PASS}
    command:
      - -n
      - --fingerprint
      - --lt-cred-mech
      - --realm=${TURN_REALM}
      - --user=${TURN_USER}:${TURN_PASS}
      - --no-stdout-log
      - --listening-port=3478
      - --tls-listening-port=5349
      - --no-tlsv1
      - --no-tlsv1_1
      - --cert=/certs/fullchain.pem
      - --pkey=/certs/privkey.pem
    volumes:
      - ./nginx/certs:/certs:ro

  nginx:
    image: nginx:stable
    depends_on: [mediamtx, ptz-proxy]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/letsencrypt
      - ./web:/usr/share/nginx/html:ro
    restart: unless-stopped

